### PR TITLE
Fixes various warnings in msgsys

### LINKED ISSUE #1103: [msgsys] Several PHP Warnings
WhatsApp Image 2024-04-05 at 22 32 27
WhatsApp Image 2024-04-05 at 22 32 29

### PR DESCRIPTION
**Pull request by M4LuZ**
### What is this PR doing?

Fixes various warnings noted and simplified/updated some of the code

### Which issue(s) this PR fixes:

Fixes #1103

### Checklist

- [x] `CHANGELOG.md` entry
- [ ] ~Documentation update~

### CODE REVIEW

File: modules/msgsys/add.php [hunk 1]
```diff
@@ -16,54 +16,51 @@
...
+                 "SELECT id
                   FROM %prefix%buddys
-                  WHERE userid =%int%", $auth['userid']);
-                $user_num = $db->num_rows();
-                if ($user_num >= 20) {
-                    $to_many_users = 1;
-                }
+                  WHERE userid = ?", [$auth['userid']]);
+
+                $too_many_users = sizeof($user_num) >= 20;
```
Comment (andygrunwald) [inline modules/msgsys/add.php:48]:
```suggestion
                $too_many_users = count($user_num) >= 20;
```

`sizeof()` is only an alias from `count()`. See https://www.php.net/manual/de/function.sizeof.php
Lets use the original instead.

File: CHANGELOG.md [hunk 2]
```diff
@@ -142,6 +142,7 @@ We could not reconstruct _all_ changes, but we tried our best to make the most o
 - [Guestlist] Restrict user information shown on Google Maps according to their settings and never show the street details ... unless you are an administrator
 - [Board] Deletion of board failed without error (#861)
 - [Forms] Hours and Minutes are not getting pre-selected in date time fields, if they are single digit (#971)
+- [Msgsys] Fixed various warnings (#1103)
```
Comment (andygrunwald) [inline CHANGELOG.md:145]:
```suggestion
```

Most of the warnings are introduced due to the PHP 8 upgrade. Hence, we did not add this to the changelog at all. Lets continue with this tradition :)

**Review by andygrunwald — APPROVED** [review]
