### PR TITLE
Fixed issue that no admin user is created in wizzard

### LINKED ISSUE #1136: Wizard - Creation of Admin user not possible
In the wizard on step 7 , I would like to create an admin user  but this fails. I cannot continue with the installation.

## Expected Behavior

The admin should be created based on the input and the process continues.

## Current Behavior
Bildschirmfoto 2024-05-21 um 15 57 58

The admin is not created and error messages appear

## Possible Solution

Implement method to create the user during the wizard or provide a workaround

```
    // Create Adminaccount
    case 7:
        //@TODO: Add the functionality here or remove the code
        break;
```

## Steps to Reproduce (for bugs)

1. Fresh installation of landsite
2. Go through the wizard until admin creation (Step 7)
3. Try to create a new admin

## Context

Cannot install the application

## Your Environment

* Version used: master
* Operating System and version: Debian 12
* Enabled features: N/A

### PR DESCRIPTION
**Pull request by M4LuZ**
### What is this PR doing?

fixes issue caused by too accurate comparison in `wizzard.php` after implementation of `$database`.

Installer checked if return value from `$database->queryWithOnlyFirstRow` was not type equal to `false`.
But the new class returns an empty array when no entry is found, which does not compare to boolean false.
Thus the installer ran the update case, which did nothing as no entry existed.

This is fixed by just comparing against `$row`, as that covers everything that is not an actual resultset

While I was at it also the related queries have been transferred to use `$database` and also some warning from index.php that popped up as warning.
Also transparent transfer after user creation to next step was implemented.

### Which issue(s) this PR fixes:

Fixes #1136, #1191

### Checklist

- [x] `CHANGELOG.md` entry
- [ ] ~Documentation update~

### CODE REVIEW

File: modules/install/wizard.php [hunk 1]
```diff
@@ -27,25 +27,24 @@
...
-                    $_POST["email"]
-                );
-            // If not found, insert
-            } else {
-                $db->qry(
-                    "INSERT INTO %prefix%user SET username = 'ADMIN', firstname = 'ADMIN', name = 'ADMIN', email=%string%, password = %string%, type = '3', lastlogin = NOW(), comment = '', birthday = NULL, signature = ''",
-                    $_POST["email"],
-                    md5($_POST["password"])
-                );
-                $userid = $db->insert_id();
```
Comment (andygrunwald) [inline modules/install/wizard.php:43]: Are we 100% sure that `$userid` is not used in an include context?
Because this is not retrieved in the new code.

**Review by andygrunwald — APPROVED** [review]
Looks good (only one small comment, but I did a quick check and was not able to find it)

File: modules/install/wizard.php (hunk 1 above)
Comment (M4LuZ) [reply modules/install/wizard.php:43]: Hi Andy,

I had the same thought, but there was no other occurrence in the file and multiple end-to-end runs of the installer showed no warnings or issues.

My guess is that this was an leftover from when login functionality was transferred to `Auth->login`
