### PR TITLE
902 show day in timetable

### LINKED ISSUE #902: Turnierplan zeigt kein Datum
Ich bin gerade gefragt worden woran man erkennen soll, an welcher Wochentag gemeint ist mit den Uhrzeiten, die man sieht, wenn man auf "Turniere-->Zeitplan" klickt.
Gute Frage, da sind nur Uhrzeiten.

## Expected Behavior
Nicht nur Uhrzeit, sondern auch Datum des gemeinten Tages einblenden.

## Current Behavior
Kein Datum eingblendet, nur Uhrzeit (aber von welchem Tag?).

## Possible Solution
Datum und Uhrzeit einblenden oder einen Tab pro Datum.

## Steps to Reproduce (for bugs)
Click here https://gybralanre.de/index.php?mod=tournament2&action=timetable

## Context
Gäste wissen nicht an welchem Tag um 22 Uhr das Turnier losgeht. Freitag? Samstag? Sonntag (natürlich nicht, aber so weit denken Gäste nicht)?

## Your Environment
Lansuite latest

### PR DESCRIPTION
**Pull request by M4LuZ**
### What is this PR doing?

Adds shortcode for the day of the week to the tournament timetable

### Which issue(s) this PR fixes:

Fixes #902

### Checklist

- [x] `CHANGELOG.md` entry
- [x] ~Documentation update~

### CODE REVIEW

File: modules/tournament2/timetable.php [hunk 1]
```diff
@@ -10,17 +10,19 @@
 // Generate Table-head
 $mintime = 9_999_999_999;
 $maxtime = 0;
-$tournaments = $db->qry("
-  SELECT *,
+//@TODO: ^rework these - values do not make sense in contect of functionality
+
+$tournaments = $database->queryWithFullResult(
+  "SELECT *,
```
Comment (andygrunwald) [inline modules/tournament2/timetable.php:16]: What do you think replacing `*` with all fields from the `tournament_tournaments` table?

I prefer an explicit listing. Mainly because it enables searching for the usage of a database field. It's not a merge blocker, but I think we should make this codebase more explicit.

File: modules/tournament2/timetable.php [hunk 2]
```diff
@@ -37,32 +39,31 @@
...
 }
 $smarty->assign('head', $head);
 
 // Generate Table-foot
 $rows = "";
-$tournaments = $db->qry("
-  SELECT
+$tournaments = $database->queryWithFullResult(
+    "SELECT
     *,
```
Comment (andygrunwald) [inline modules/tournament2/timetable.php:57]: Same here about listing the explicit fields.

**Review by andygrunwald — APPROVED** [review]
Good one! I like it. Only the comments with the `SELECT *` fields. This is up to you. Feel free to merge it or first changing the field listing.

File: modules/tournament2/timetable.php (hunk 2 above)
Comment (M4LuZ) [reply modules/tournament2/timetable.php]: This was actually solved by removing the query alltogether, as it is a 1:1 duplicate of the one above and the whole resultset has already been fetched into `$tournaments` and thus can just be iterated through again

File: modules/tournament2/timetable.php (hunk 1 above)
Comment (M4LuZ) [reply modules/tournament2/timetable.php]: Done. It was a bit more complicated as some fields are implicitly used by `$tfunc->GetGameEnd()`, but that was solved by a bit of pen&paper ;)
