### PR TITLE
Fix #103: Generate PHP API docs for production release

### LINKED ISSUE #103: Test v3.0.0-alpha1 of phpDocumentor2
A new version of phpDocumentor2 (https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v3.0.0-alpha1) was released a week ago.

## Expected Behavior

Should generate the documentation of lansuite propery without errors.

## Current Behavior

The generation of the documentation throws several errors under PHP7.

## Possible Solution

Upgrade phpDocumentor2 to v3.0.0

## Steps to Reproduce (for bugs)

1. Checkout lansuite
2. Hit composer install
3. Try to generate the documentation like described in the README with >= PHP 7

## Context

LanSuite ships a API documentation with it.
This documentation is typically generated with phpDocumentor2

### PR DESCRIPTION
**Pull request by andygrunwald**
## Context

We install https://www.phpdoc.org/ and generate the PHP API docs for the production release.
Those are getting stored in `/docs/api`.

Furthermore
* fixed a missing whitespace
* fixed a missing line return
* removed verbose flag from tar to be able to track the log output

## Tickets

Fix #103

### CODE REVIEW

**Comment by andygrunwald** [comment]
@M4LuZ Any possibility for a review?

File: bin/prepare-release.sh [hunk 1]
```diff
@@ -160,7 +170,7 @@ tar --exclude .git \
     --exclude Dockerfile-Production-Release \
     --exclude docker-compose.yml \
     --exclude docker-compose.dump.yml \
-    -cvzf "${OUTPUT_DIR}$LANSUITE_FILENAME.tar.gz" .
+    -czf "${OUTPUT_DIR}$LANSUITE_FILENAME.tar.gz" .
```
Comment (M4LuZ) [inline bin/prepare-release.sh:173]: `zip`may be a better format here, although I would see leave as-is and see if we get any requests / questions in that regard

**Review by M4LuZ — APPROVED** [review]
