### PR TITLE
Fix not working board delete

### LINKED ISSUE #861: Masterdelete / Board: Forum deletion fails without error
## Expected Behavior

When clicking the icon to delete a Board it should either remove it or at least report _somewhere_ that it had an issue

## Current Behavior

clicking the related icon just shows the overview page with the board still there.
No error displayed, nothing in the log.
Normally a confirmation display should be shown.

Deleting threads and comments works as expected.

## Possible Solution

1. See if this is an issue with the call from `board/delete.php` and fix it
2. See if this is an issue with the `MasterDelete` class and fix it
3. Replace delegation to `MasterDelete` with native code as part of the class or separate function

## Steps to Reproduce (for bugs)

1. Create a board
2. Click on the deletion icon

## Context

I found this while validating functionality after refactoring `board/thread.php` to use the new db class

## Your Environment

* Version used: Git master
* Operating System and version: Win 10, PHP 8.2, MySQL 8.0
* Enabled features:

### PR DESCRIPTION
**Pull request by M4LuZ**
### What is this PR doing?

adds implit typecasting to int for match statement to hit cases `2` and `10`
This failed previously due to `$stepParameter` being a string and thus always the default case to display the board was exected

### Which issue(s) this PR fixes:

Fixes #861 

### Checklist

- [x] `CHANGELOG.md` entry
- [x] ~Documentation update~ (bugfix only)

### CODE REVIEW

File: modules/board/delete.php [hunk 1]
```diff
@@ -16,7 +16,7 @@
 
 // Delete board
 } else {
-    match ($stepParameter) {
+    match ((int)$stepParameter) {
```
Comment (andygrunwald) [inline modules/board/delete.php:19]: What do you think about adding
```
$stepParameter = $_GET['step'] ?? 0;
$stepParameter = (int) $stepParameter;
```

on top of the file? This would ensure the parameter is always an integer and not only in this particular match case. I can't think of a scenario, where a string would be beneficial here.

**Review by andygrunwald — CHANGES_REQUESTED** [review]

File: modules/board/delete.php (hunk 1 above)
Comment (M4LuZ) [reply modules/board/delete.php:19]: Now that you forced me to think about it again:
I would say the best way would be to use `$request->query->getInt('step',0)`.
As that enforces a default value, does the type casting and refactors already to utilize functionality of HttpFoundation.
I would be so lazy to drop that directly into the match statement, but I guess the cleaner way would be to initialize a variable on top. 
And yes, all of those step variables are integers...which is also we may want to change or at least define as constants

**Comment by M4LuZ** [comment]
Hi Andy.,

I am aware that there are some cases where values are written back to the superglobals(most prominently the escaping of values also in index.php), but this is not one of them.
So my thought is that this can be replaced bit by bit, as long as we are aware of these fringe cases and solve them before touching the code where values are accessed.

**Comment by andygrunwald** [comment]
@M4LuZ If we do it bit by bit, I suggest we focus on the writes first because those are mostly the lines that produce the bugs.

I am good with merging it. Thanks for finding it!

**Review by andygrunwald — APPROVED** [review]
